/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardSupportBACKUPRouteImport } from './routes/dashboard/support-BACKUP'
import { Route as DashboardSupportRouteImport } from './routes/dashboard/support'
import { Route as DashboardSubscriptionsRouteImport } from './routes/dashboard/subscriptions'
import { Route as DashboardSettingsBACKUPRouteImport } from './routes/dashboard/settings-BACKUP'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardReportsBACKUPRouteImport } from './routes/dashboard/reports-BACKUP'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardOrganisationsRouteImport } from './routes/dashboard/organisations'
import { Route as DashboardAuditLogsBACKUPRouteImport } from './routes/dashboard/audit-logs-BACKUP'
import { Route as DashboardAuditLogsRouteImport } from './routes/dashboard/audit-logs'
import { Route as DashboardAnnouncementsBACKUPRouteImport } from './routes/dashboard/announcements-BACKUP'
import { Route as DashboardAnnouncementsRouteImport } from './routes/dashboard/announcements'
import { Route as DashboardAlertsRouteImport } from './routes/dashboard/alerts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/dashboard/users',
  path: '/dashboard/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSupportBACKUPRoute = DashboardSupportBACKUPRouteImport.update({
  id: '/dashboard/support-BACKUP',
  path: '/dashboard/support-BACKUP',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/dashboard/support',
  path: '/dashboard/support',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSubscriptionsRoute = DashboardSubscriptionsRouteImport.update({
  id: '/dashboard/subscriptions',
  path: '/dashboard/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsBACKUPRoute = DashboardSettingsBACKUPRouteImport.update({
  id: '/dashboard/settings-BACKUP',
  path: '/dashboard/settings-BACKUP',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsBACKUPRoute = DashboardReportsBACKUPRouteImport.update({
  id: '/dashboard/reports-BACKUP',
  path: '/dashboard/reports-BACKUP',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/dashboard/reports',
  path: '/dashboard/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrganisationsRoute = DashboardOrganisationsRouteImport.update({
  id: '/dashboard/organisations',
  path: '/dashboard/organisations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuditLogsBACKUPRoute =
  DashboardAuditLogsBACKUPRouteImport.update({
    id: '/dashboard/audit-logs-BACKUP',
    path: '/dashboard/audit-logs-BACKUP',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAuditLogsRoute = DashboardAuditLogsRouteImport.update({
  id: '/dashboard/audit-logs',
  path: '/dashboard/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAnnouncementsBACKUPRoute =
  DashboardAnnouncementsBACKUPRouteImport.update({
    id: '/dashboard/announcements-BACKUP',
    path: '/dashboard/announcements-BACKUP',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAnnouncementsRoute = DashboardAnnouncementsRouteImport.update({
  id: '/dashboard/announcements',
  path: '/dashboard/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/dashboard/alerts',
  path: '/dashboard/alerts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/announcements-BACKUP': typeof DashboardAnnouncementsBACKUPRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/dashboard/audit-logs-BACKUP': typeof DashboardAuditLogsBACKUPRoute
  '/dashboard/organisations': typeof DashboardOrganisationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/reports-BACKUP': typeof DashboardReportsBACKUPRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/settings-BACKUP': typeof DashboardSettingsBACKUPRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/support-BACKUP': typeof DashboardSupportBACKUPRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/announcements-BACKUP': typeof DashboardAnnouncementsBACKUPRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/dashboard/audit-logs-BACKUP': typeof DashboardAuditLogsBACKUPRoute
  '/dashboard/organisations': typeof DashboardOrganisationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/reports-BACKUP': typeof DashboardReportsBACKUPRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/settings-BACKUP': typeof DashboardSettingsBACKUPRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/support-BACKUP': typeof DashboardSupportBACKUPRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/announcements-BACKUP': typeof DashboardAnnouncementsBACKUPRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/dashboard/audit-logs-BACKUP': typeof DashboardAuditLogsBACKUPRoute
  '/dashboard/organisations': typeof DashboardOrganisationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/reports-BACKUP': typeof DashboardReportsBACKUPRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/settings-BACKUP': typeof DashboardSettingsBACKUPRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/support-BACKUP': typeof DashboardSupportBACKUPRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard/alerts'
    | '/dashboard/announcements'
    | '/dashboard/announcements-BACKUP'
    | '/dashboard/audit-logs'
    | '/dashboard/audit-logs-BACKUP'
    | '/dashboard/organisations'
    | '/dashboard/reports'
    | '/dashboard/reports-BACKUP'
    | '/dashboard/settings'
    | '/dashboard/settings-BACKUP'
    | '/dashboard/subscriptions'
    | '/dashboard/support'
    | '/dashboard/support-BACKUP'
    | '/dashboard/users'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/alerts'
    | '/dashboard/announcements'
    | '/dashboard/announcements-BACKUP'
    | '/dashboard/audit-logs'
    | '/dashboard/audit-logs-BACKUP'
    | '/dashboard/organisations'
    | '/dashboard/reports'
    | '/dashboard/reports-BACKUP'
    | '/dashboard/settings'
    | '/dashboard/settings-BACKUP'
    | '/dashboard/subscriptions'
    | '/dashboard/support'
    | '/dashboard/support-BACKUP'
    | '/dashboard/users'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/dashboard/alerts'
    | '/dashboard/announcements'
    | '/dashboard/announcements-BACKUP'
    | '/dashboard/audit-logs'
    | '/dashboard/audit-logs-BACKUP'
    | '/dashboard/organisations'
    | '/dashboard/reports'
    | '/dashboard/reports-BACKUP'
    | '/dashboard/settings'
    | '/dashboard/settings-BACKUP'
    | '/dashboard/subscriptions'
    | '/dashboard/support'
    | '/dashboard/support-BACKUP'
    | '/dashboard/users'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardAnnouncementsRoute: typeof DashboardAnnouncementsRoute
  DashboardAnnouncementsBACKUPRoute: typeof DashboardAnnouncementsBACKUPRoute
  DashboardAuditLogsRoute: typeof DashboardAuditLogsRoute
  DashboardAuditLogsBACKUPRoute: typeof DashboardAuditLogsBACKUPRoute
  DashboardOrganisationsRoute: typeof DashboardOrganisationsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardReportsBACKUPRoute: typeof DashboardReportsBACKUPRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSettingsBACKUPRoute: typeof DashboardSettingsBACKUPRoute
  DashboardSubscriptionsRoute: typeof DashboardSubscriptionsRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardSupportBACKUPRoute: typeof DashboardSupportBACKUPRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/dashboard/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/support-BACKUP': {
      id: '/dashboard/support-BACKUP'
      path: '/dashboard/support-BACKUP'
      fullPath: '/dashboard/support-BACKUP'
      preLoaderRoute: typeof DashboardSupportBACKUPRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/dashboard/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/subscriptions': {
      id: '/dashboard/subscriptions'
      path: '/dashboard/subscriptions'
      fullPath: '/dashboard/subscriptions'
      preLoaderRoute: typeof DashboardSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings-BACKUP': {
      id: '/dashboard/settings-BACKUP'
      path: '/dashboard/settings-BACKUP'
      fullPath: '/dashboard/settings-BACKUP'
      preLoaderRoute: typeof DashboardSettingsBACKUPRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports-BACKUP': {
      id: '/dashboard/reports-BACKUP'
      path: '/dashboard/reports-BACKUP'
      fullPath: '/dashboard/reports-BACKUP'
      preLoaderRoute: typeof DashboardReportsBACKUPRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/dashboard/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/organisations': {
      id: '/dashboard/organisations'
      path: '/dashboard/organisations'
      fullPath: '/dashboard/organisations'
      preLoaderRoute: typeof DashboardOrganisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/audit-logs-BACKUP': {
      id: '/dashboard/audit-logs-BACKUP'
      path: '/dashboard/audit-logs-BACKUP'
      fullPath: '/dashboard/audit-logs-BACKUP'
      preLoaderRoute: typeof DashboardAuditLogsBACKUPRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/audit-logs': {
      id: '/dashboard/audit-logs'
      path: '/dashboard/audit-logs'
      fullPath: '/dashboard/audit-logs'
      preLoaderRoute: typeof DashboardAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/announcements-BACKUP': {
      id: '/dashboard/announcements-BACKUP'
      path: '/dashboard/announcements-BACKUP'
      fullPath: '/dashboard/announcements-BACKUP'
      preLoaderRoute: typeof DashboardAnnouncementsBACKUPRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/announcements': {
      id: '/dashboard/announcements'
      path: '/dashboard/announcements'
      fullPath: '/dashboard/announcements'
      preLoaderRoute: typeof DashboardAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/alerts': {
      id: '/dashboard/alerts'
      path: '/dashboard/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardAnnouncementsRoute: DashboardAnnouncementsRoute,
  DashboardAnnouncementsBACKUPRoute: DashboardAnnouncementsBACKUPRoute,
  DashboardAuditLogsRoute: DashboardAuditLogsRoute,
  DashboardAuditLogsBACKUPRoute: DashboardAuditLogsBACKUPRoute,
  DashboardOrganisationsRoute: DashboardOrganisationsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardReportsBACKUPRoute: DashboardReportsBACKUPRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSettingsBACKUPRoute: DashboardSettingsBACKUPRoute,
  DashboardSubscriptionsRoute: DashboardSubscriptionsRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardSupportBACKUPRoute: DashboardSupportBACKUPRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
